version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: firebase
    versions:
    - "> 7.14.4"
  - dependency-name: moment
    versions:
    - "> 2.25.3"
  - dependency-name: sass
    versions:
    - "> 1.26.5"
  - dependency-name: "@vue/cli-plugin-router"
    versions:
    - "> 4.3.1"
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.9.0
    - 3.9.1
  - dependency-name: vuetify
    versions:
    - 2.4.3
    - 2.4.4
    - 2.4.5
    - 2.4.6
    - 2.4.7
    - 2.4.8
    - 2.4.9
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
    - 7.6.0
    - 7.7.0
    - 7.8.0
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.11
  - dependency-name: vue-cli-plugin-vuetify
    versions:
    - 2.1.0
  - dependency-name: vue-router
    versions:
    - 3.5.0
